2023-05-13T08:18:42 [     393] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:18:42 [     457] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:18:44 [     692] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:18:45 [     934] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-pwbm",{"micros":132825,"calls":["id_created",{"micros":874,"calls":[]},"session_lookup_time",{"micros":2494,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-196",{"micros":128113,"calls":["start_session",{"micros":70360,"calls":["discord-api-7c8b45696-7q8h2",{"micros":65710,"calls":["get_user",{"micros":23990},"get_guilds",{"micros":6222},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":60,"calls":[]},"presence_started",{"micros":19263,"calls":[]},"guilds_started",{"micros":100,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":38273,"calls":[]},"connect_finished",{"micros":38279,"calls":[]},"build_ready",{"micros":22,"calls":[]},"clean_ready",{"micros":26,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 273a5a0770282dd03c6870ae9b849739).
2023-05-13T08:19:24 [     980] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:19:25 [      27] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:19:28 [     528] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:19:28 [     980] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-255p",{"micros":193827,"calls":["id_created",{"micros":1230,"calls":[]},"session_lookup_time",{"micros":307,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-168",{"micros":191953,"calls":["start_session",{"micros":96688,"calls":["discord-api-7c8b45696-6lgp4",{"micros":74997,"calls":["get_user",{"micros":21647},"get_guilds",{"micros":14945},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":299},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":43241,"calls":[]},"guilds_started",{"micros":82,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":51849,"calls":[]},"connect_finished",{"micros":51853,"calls":[]},"build_ready",{"micros":17,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":18,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 79293b72753a382b63e880e2ec98d51d).
2023-05-13T08:20:15 [     877] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:20:15 [     965] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:20:16 [     497] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:20:16 [     695] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-mr73",{"micros":74768,"calls":["id_created",{"micros":1598,"calls":[]},"session_lookup_time",{"micros":2284,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-198",{"micros":69769,"calls":["start_session",{"micros":46669,"calls":["discord-api-7c8b45696-cmmmm",{"micros":41808,"calls":["get_user",{"micros":13261},"get_guilds",{"micros":3584},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":933},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":52,"calls":[]},"presence_started",{"micros":284,"calls":[]},"guilds_started",{"micros":98,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":22623,"calls":[]},"connect_finished",{"micros":22627,"calls":[]},"build_ready",{"micros":15,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":21,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 13bb2cb198288e1d809d74d7c520eef9).
2023-05-13T08:50:02 [     557] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:50:02 [     612] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:50:02 [     650] INFO    : client          @run              #712  : Cleaning up tasks.
2023-05-13T08:50:02 [     650] INFO    : client          @_cleanup_loop    #112  : Closing the event loop.
2023-05-13T08:50:36 [      66] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:50:36 [     108] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:50:36 [     648] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:50:36 [     920] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-rjm9",{"micros":152941,"calls":["id_created",{"micros":927,"calls":[]},"session_lookup_time",{"micros":2143,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-282",{"micros":149315,"calls":["start_session",{"micros":90480,"calls":["discord-api-7c8b45696-29pq7",{"micros":85059,"calls":["get_user",{"micros":16485},"get_guilds",{"micros":9492},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":266},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":49,"calls":[]},"presence_started",{"micros":372,"calls":[]},"guilds_started",{"micros":99,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":58264,"calls":[]},"connect_finished",{"micros":58271,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":23,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 3e8e71f4f7fb76f4ff5584e892ffad95).
2023-05-13T08:55:20 [      87] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:55:20 [     127] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:55:20 [     152] INFO    : client          @run              #712  : Cleaning up tasks.
2023-05-13T08:55:20 [     153] INFO    : client          @_cleanup_loop    #112  : Closing the event loop.
2023-05-13T08:55:33 [     395] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:55:33 [     433] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:55:34 [       0] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:55:34 [     224] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-6gbq",{"micros":109373,"calls":["id_created",{"micros":2469,"calls":[]},"session_lookup_time",{"micros":292,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-258",{"micros":105773,"calls":["start_session",{"micros":48059,"calls":["discord-api-7c8b45696-pxfmj",{"micros":43487,"calls":["get_user",{"micros":14732},"get_guilds",{"micros":4018},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":50,"calls":[]},"presence_started",{"micros":327,"calls":[]},"guilds_started",{"micros":93,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":57192,"calls":[]},"connect_finished",{"micros":57198,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":22,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 44c375e30295069f510a9ef4dde62d36).
2023-05-13T08:56:55 [     804] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:56:55 [     845] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:56:56 [     429] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:56:56 [     710] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-37xv",{"micros":159047,"calls":["id_created",{"micros":1199,"calls":[]},"session_lookup_time",{"micros":4270,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-25",{"micros":151970,"calls":["start_session",{"micros":107500,"calls":["discord-api-7c8b45696-9qzqm",{"micros":99291,"calls":["get_user",{"micros":30231},"get_guilds",{"micros":10324},"send_scheduled_deletion_message",{"micros":15},"guild_join_requests",{"micros":3501},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":64,"calls":[]},"presence_started",{"micros":225,"calls":[]},"guilds_started",{"micros":76,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":44060,"calls":[]},"connect_finished",{"micros":44066,"calls":[]},"build_ready",{"micros":17,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":19,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 8fe8078f32e4bc93febbe66dfcb2b605).
2023-05-13T08:58:03 [     153] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:58:03 [     198] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:58:03 [     721] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:58:03 [     931] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-tzc7",{"micros":93558,"calls":["id_created",{"micros":925,"calls":[]},"session_lookup_time",{"micros":448,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-53",{"micros":91552,"calls":["start_session",{"micros":58954,"calls":["discord-api-7c8b45696-fk7rg",{"micros":51420,"calls":["get_user",{"micros":20281},"get_guilds",{"micros":3690},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":5557},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":67,"calls":[]},"presence_started",{"micros":275,"calls":[]},"guilds_started",{"micros":61,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":32151,"calls":[]},"connect_finished",{"micros":32155,"calls":[]},"build_ready",{"micros":17,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":20,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 97c83512d59a7e4b6169495af6be0e89).
2023-05-13T08:58:29 [      58] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T08:58:29 [      95] INFO    : client          @login            #513  : logging in using static token
2023-05-13T08:58:29 [     590] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T08:58:29 [     850] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-b22p",{"micros":147131,"calls":["id_created",{"micros":1277,"calls":[]},"session_lookup_time",{"micros":348,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-227",{"micros":145165,"calls":["start_session",{"micros":67351,"calls":["discord-api-7c8b45696-m4vtk",{"micros":53174,"calls":["get_user",{"micros":17416},"get_guilds",{"micros":4000},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1135},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":49,"calls":[]},"presence_started",{"micros":368,"calls":[]},"guilds_started",{"micros":73,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":77240,"calls":[]},"connect_finished",{"micros":77246,"calls":[]},"build_ready",{"micros":27,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":47,"calls":[]}]}]}] (Session ID: a4c339e4f9968a3fe1a6358e6f440477).
2023-05-13T09:00:19 [     303] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:00:19 [     348] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:00:19 [     940] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:00:20 [     156] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-wr6g",{"micros":99480,"calls":["id_created",{"micros":932,"calls":[]},"session_lookup_time",{"micros":268,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-271",{"micros":97579,"calls":["start_session",{"micros":52917,"calls":["discord-api-7c8b45696-lvfr5",{"micros":49358,"calls":["get_user",{"micros":15434},"get_guilds",{"micros":4012},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":48,"calls":[]},"presence_started",{"micros":268,"calls":[]},"guilds_started",{"micros":69,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":44238,"calls":[]},"connect_finished",{"micros":44242,"calls":[]},"build_ready",{"micros":15,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":18,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: ae38183dd93b287f3efbadd0abd0a825).
2023-05-13T09:01:08 [     922] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:01:08 [     961] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:01:09 [     472] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:01:09 [     704] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-255p",{"micros":121710,"calls":["id_created",{"micros":1815,"calls":[]},"session_lookup_time",{"micros":1940,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-252",{"micros":117557,"calls":["start_session",{"micros":85174,"calls":["discord-api-7c8b45696-w2xdr",{"micros":74136,"calls":["get_user",{"micros":28935},"get_guilds",{"micros":6454},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":61,"calls":[]},"presence_started",{"micros":288,"calls":[]},"guilds_started",{"micros":101,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":31882,"calls":[]},"connect_finished",{"micros":31887,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":25,"calls":[]}]}]}] (Session ID: 7d318f72b789ac9b74c7c2efab49b89d).
2023-05-13T09:06:18 [     291] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:06:18 [     336] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:06:18 [     916] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:06:19 [     147] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-23j6",{"micros":120282,"calls":["id_created",{"micros":1781,"calls":[]},"session_lookup_time",{"micros":5577,"calls":[]},"session_lookup_finished",{"micros":20,"calls":[]},"discord-sessions-prd-2-218",{"micros":111708,"calls":["start_session",{"micros":47262,"calls":["discord-api-7c8b45696-jtz7s",{"micros":42376,"calls":["get_user",{"micros":12545},"get_guilds",{"micros":4188},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":48,"calls":[]},"presence_started",{"micros":235,"calls":[]},"guilds_started",{"micros":63,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":64046,"calls":[]},"connect_finished",{"micros":64051,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":25,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 77a9b93aaf02f93733c73f4dd1e594f4).
2023-05-13T09:07:02 [     186] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:07:02 [     227] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:07:02 [     726] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:07:02 [     949] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-sz43",{"micros":109441,"calls":["id_created",{"micros":962,"calls":[]},"session_lookup_time",{"micros":233,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-114",{"micros":107754,"calls":["start_session",{"micros":76187,"calls":["discord-api-7c8b45696-9rsj9",{"micros":71133,"calls":["get_user",{"micros":18662},"get_guilds",{"micros":8072},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":39}]}]},"starting_guild_connect",{"micros":59,"calls":[]},"presence_started",{"micros":285,"calls":[]},"guilds_started",{"micros":80,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":31099,"calls":[]},"connect_finished",{"micros":31102,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":20,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 7715814e28fd92c883c58ca697b27af2).
2023-05-13T09:07:19 [     335] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:07:19 [     381] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:07:19 [     867] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:07:20 [     119] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-5m8k",{"micros":141951,"calls":["id_created",{"micros":1149,"calls":[]},"session_lookup_time",{"micros":404,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-280",{"micros":139289,"calls":["start_session",{"micros":82069,"calls":["discord-api-7c8b45696-52q9v",{"micros":77795,"calls":["get_user",{"micros":30487},"get_guilds",{"micros":7779},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":46,"calls":[]},"presence_started",{"micros":194,"calls":[]},"guilds_started",{"micros":88,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":56832,"calls":[]},"connect_finished",{"micros":56838,"calls":[]},"build_ready",{"micros":22,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":27,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: b4452512d61d0780b251b8bdd995e59e).
2023-05-13T09:07:36 [     986] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:07:37 [      30] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:07:37 [     548] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:07:37 [     777] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-37xv",{"micros":102334,"calls":["id_created",{"micros":827,"calls":[]},"session_lookup_time",{"micros":4971,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-43",{"micros":96002,"calls":["start_session",{"micros":74834,"calls":["discord-api-7c8b45696-7q8h2",{"micros":71829,"calls":["get_user",{"micros":25916},"get_guilds",{"micros":8704},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":56,"calls":[]},"presence_started",{"micros":191,"calls":[]},"guilds_started",{"micros":72,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":20798,"calls":[]},"connect_finished",{"micros":20804,"calls":[]},"build_ready",{"micros":22,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":20,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 062a342098e9081313119e64d883592e).
2023-05-13T09:08:09 [     337] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:08:09 [     379] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:08:09 [     895] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:08:10 [     139] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-tqwj",{"micros":127067,"calls":["id_created",{"micros":838,"calls":[]},"session_lookup_time",{"micros":15669,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-184",{"micros":109534,"calls":["start_session",{"micros":78335,"calls":["discord-api-7c8b45696-tl7kp",{"micros":70392,"calls":["get_user",{"micros":19181},"get_guilds",{"micros":5347},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":57,"calls":[]},"presence_started",{"micros":30674,"calls":[]},"guilds_started",{"micros":90,"calls":[]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":304,"calls":[]},"connect_finished",{"micros":312,"calls":[]},"build_ready",{"micros":37,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":26,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: e3093abc95cb08eceed94d34ba153d29).
2023-05-13T09:09:16 [     904] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:09:16 [     943] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:09:17 [     428] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:09:17 [     716] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-4m58",{"micros":174789,"calls":["id_created",{"micros":1706,"calls":[]},"session_lookup_time",{"micros":336,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-293",{"micros":171697,"calls":["start_session",{"micros":120900,"calls":["discord-api-7c8b45696-q2szr",{"micros":116244,"calls":["get_user",{"micros":41766},"get_guilds",{"micros":16136},"send_scheduled_deletion_message",{"micros":13},"guild_join_requests",{"micros":3},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":44,"calls":[]},"presence_started",{"micros":239,"calls":[]},"guilds_started",{"micros":73,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":50388,"calls":[]},"connect_finished",{"micros":50393,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":26,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 3f17c42bef7afa1f057442c762ff41bf).
2023-05-13T09:24:12 [     759] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:24:12 [     800] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:24:13 [     375] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:24:13 [     631] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-3sc8",{"micros":125222,"calls":["id_created",{"micros":636,"calls":[]},"session_lookup_time",{"micros":8890,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-136",{"micros":114901,"calls":["start_session",{"micros":75654,"calls":["discord-api-7c8b45696-vm4l5",{"micros":67922,"calls":["get_user",{"micros":22233},"get_guilds",{"micros":7459},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":47,"calls":[]},"presence_started",{"micros":18060,"calls":[]},"guilds_started",{"micros":107,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":20975,"calls":[]},"connect_finished",{"micros":20980,"calls":[]},"build_ready",{"micros":25,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":24,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 79372e3325f157ac08449e0914c75b64).
2023-05-13T09:25:40 [     774] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:25:40 [     823] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:25:41 [     327] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:25:41 [     520] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-wz7g",{"micros":64923,"calls":["id_created",{"micros":1529,"calls":[]},"session_lookup_time",{"micros":370,"calls":[]},"session_lookup_finished",{"micros":19,"calls":[]},"discord-sessions-prd-2-200",{"micros":62626,"calls":["start_session",{"micros":42026,"calls":["discord-api-7c8b45696-pkz6v",{"micros":38141,"calls":["get_user",{"micros":12314},"get_guilds",{"micros":3600},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":209},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":49,"calls":[]},"presence_started",{"micros":245,"calls":[]},"guilds_started",{"micros":83,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":20155,"calls":[]},"connect_finished",{"micros":20166,"calls":[]},"build_ready",{"micros":25,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":30,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 6fd6e90f82896708e9f50e203457fa68).
2023-05-13T09:27:09 [     679] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T09:27:09 [     718] INFO    : client          @login            #513  : logging in using static token
2023-05-13T09:27:10 [     305] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T09:27:10 [     494] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-zbrx",{"micros":78360,"calls":["id_created",{"micros":1662,"calls":[]},"session_lookup_time",{"micros":4805,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-143",{"micros":70541,"calls":["start_session",{"micros":50890,"calls":["discord-api-7c8b45696-sg2l7",{"micros":46478,"calls":["get_user",{"micros":13920},"get_guilds",{"micros":7121},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":55,"calls":[]},"presence_started",{"micros":400,"calls":[]},"guilds_started",{"micros":83,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":19066,"calls":[]},"connect_finished",{"micros":19071,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":22,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: 5bb7765108efdeb4cd9975015be003bb).
2023-05-13T10:35:25 [     980] WARNING : gateway         @run              #142  : Shard ID None has stopped responding to the gateway. Closing and restarting.
2023-05-13T10:35:25 [     982] INFO    : gateway         @poll_event       #622  : Timed out receiving packet. Attempting a reconnect.
2023-05-13T10:35:25 [     983] INFO    : client          @connect          #556  : Got a request to RESUME the websocket.
2023-05-13T10:35:26 [     599] INFO    : gateway         @resume           #451  : Shard ID None has sent the RESUME payload.
2023-05-13T10:35:26 [     725] INFO    : gateway         @received_message #517  : Shard ID None session has been invalidated.
2023-05-13T10:56:42 [     710] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T10:56:42 [     804] INFO    : client          @login            #513  : logging in using static token
2023-05-13T10:56:43 [     376] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T10:56:43 [     630] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-20wx",{"micros":135934,"calls":["id_created",{"micros":1194,"calls":[]},"session_lookup_time",{"micros":1679,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-124",{"micros":132013,"calls":["start_session",{"micros":58800,"calls":["discord-api-7c8b45696-xs7jw",{"micros":53737,"calls":["get_user",{"micros":19250},"get_guilds",{"micros":5629},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":54,"calls":[]},"presence_started",{"micros":269,"calls":[]},"guilds_started",{"micros":65,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":72769,"calls":[]},"connect_finished",{"micros":72774,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":27,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: a868de7a3f7357f31f79df3cbfd524a5).
2023-05-13T10:58:44 [     681] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T10:58:44 [     750] INFO    : client          @login            #513  : logging in using static token
2023-05-13T10:58:45 [     499] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T10:58:45 [     741] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-1fv6",{"micros":126935,"calls":["id_created",{"micros":1715,"calls":[]},"session_lookup_time",{"micros":883,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-273",{"micros":124047,"calls":["start_session",{"micros":73468,"calls":["discord-api-7c8b45696-mhp9v",{"micros":68878,"calls":["get_user",{"micros":18199},"get_guilds",{"micros":7643},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":43,"calls":[]},"presence_started",{"micros":290,"calls":[]},"guilds_started",{"micros":88,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":50108,"calls":[]},"connect_finished",{"micros":50113,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":23,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 0288a6424b8d9393466f303b16218908).
2023-05-13T10:59:41 [     918] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T10:59:42 [      24] INFO    : client          @login            #513  : logging in using static token
2023-05-13T10:59:42 [     874] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T10:59:43 [     214] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-pbfj",{"micros":164626,"calls":["id_created",{"micros":1435,"calls":[]},"session_lookup_time",{"micros":266,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-125",{"micros":161429,"calls":["start_session",{"micros":72430,"calls":["discord-api-7c8b45696-88b7r",{"micros":54444,"calls":["get_user",{"micros":16546},"get_guilds",{"micros":5696},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":9}]}]},"starting_guild_connect",{"micros":63,"calls":[]},"presence_started",{"micros":41975,"calls":[]},"guilds_started",{"micros":82,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":46820,"calls":[]},"connect_finished",{"micros":46826,"calls":[]},"build_ready",{"micros":24,"calls":[]},"clean_ready",{"micros":26,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 80f78597cb3880d41b1952173423214f).
2023-05-13T12:02:40 [     327] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T12:02:40 [     452] INFO    : client          @login            #513  : logging in using static token
2023-05-13T12:02:41 [     435] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T12:02:41 [     666] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-mdh8",{"micros":117570,"calls":["id_created",{"micros":988,"calls":[]},"session_lookup_time",{"micros":706,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-45",{"micros":115096,"calls":["start_session",{"micros":79671,"calls":["discord-api-7c8b45696-gzr67",{"micros":73393,"calls":["get_user",{"micros":21432},"get_guilds",{"micros":16398},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":45,"calls":[]},"presence_started",{"micros":9659,"calls":[]},"guilds_started",{"micros":74,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":25601,"calls":[]},"connect_finished",{"micros":25605,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":20,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: dae57f9d8407c2b5e1b2c6e3aac02f40).
2023-05-13T12:04:16 [     449] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T12:04:16 [     564] INFO    : client          @login            #513  : logging in using static token
2023-05-13T12:04:17 [     295] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T12:04:17 [     491] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-v5ts",{"micros":79107,"calls":["id_created",{"micros":1214,"calls":[]},"session_lookup_time",{"micros":354,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-187",{"micros":76446,"calls":["start_session",{"micros":60453,"calls":["discord-api-7c8b45696-5clq7",{"micros":54462,"calls":["get_user",{"micros":16978},"get_guilds",{"micros":9629},"send_scheduled_deletion_message",{"micros":14},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":47}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":2229,"calls":[]},"guilds_started",{"micros":109,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":13555,"calls":[]},"connect_finished",{"micros":13561,"calls":[]},"build_ready",{"micros":22,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":19,"calls":[]}]}]}] (Session ID: bf956754dcbed1e4dcaf715bdec28095).
2023-05-13T12:06:36 [     621] INFO    : gateway         @poll_event       #630  : Websocket closed with 1000, cannot reconnect.
2023-05-13T12:06:36 [     621] ERROR   : client          @connect          #605  : Attempting a reconnect in 1.11s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 554, in connect
    await self.ws.poll_event()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 631, in poll_event
    raise ConnectionClosed(
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2023-05-13T12:06:38 [     164] INFO    : gateway         @resume           #451  : Shard ID None has sent the RESUME payload.
2023-05-13T12:06:38 [     280] INFO    : gateway         @received_message #542  : Shard ID None has successfully RESUMED session bf956754dcbed1e4dcaf715bdec28095 under trace ["gateway-prd-us-east1-b-wzwb",{"micros":475,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":238,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-187",{"micros":23}]}].
2023-05-13T12:10:50 [     541] WARNING : gateway         @run              #142  : Shard ID None has stopped responding to the gateway. Closing and restarting.
2023-05-13T12:10:50 [     543] INFO    : gateway         @poll_event       #622  : Timed out receiving packet. Attempting a reconnect.
2023-05-13T12:10:50 [     543] INFO    : client          @connect          #556  : Got a request to RESUME the websocket.
2023-05-13T12:10:50 [     546] ERROR   : client          @connect          #605  : Attempting a reconnect in 0.21s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T12:10:52 [     314] INFO    : gateway         @resume           #451  : Shard ID None has sent the RESUME payload.
2023-05-13T12:10:52 [     443] INFO    : gateway         @received_message #517  : Shard ID None session has been invalidated.
2023-05-13T12:10:52 [     579] INFO    : client          @connect          #556  : Got a request to IDENTIFY the websocket.
2023-05-13T12:10:58 [     278] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T12:10:58 [     551] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-zbrx",{"micros":150720,"calls":["id_created",{"micros":3286,"calls":[]},"session_lookup_time",{"micros":311,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-233",{"micros":146526,"calls":["start_session",{"micros":74874,"calls":["discord-api-7c8b45696-6nhkt",{"micros":68618,"calls":["get_user",{"micros":19077},"get_guilds",{"micros":6269},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":230},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":56,"calls":[]},"presence_started",{"micros":30412,"calls":[]},"guilds_started",{"micros":80,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":41057,"calls":[]},"connect_finished",{"micros":41061,"calls":[]},"build_ready",{"micros":17,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":22,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: d25fe4965b558c0683b02e6db4ca99c8).
2023-05-13T12:17:02 [     969] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T12:17:03 [      20] INFO    : client          @login            #513  : logging in using static token
2023-05-13T12:17:03 [     880] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T12:17:04 [      95] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-j0lc",{"micros":102221,"calls":["id_created",{"micros":784,"calls":[]},"session_lookup_time",{"micros":2114,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-273",{"micros":98335,"calls":["start_session",{"micros":42560,"calls":["discord-api-7c8b45696-ktkhz",{"micros":37168,"calls":["get_user",{"micros":11946},"get_guilds",{"micros":3881},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":643},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":59,"calls":[]},"presence_started",{"micros":365,"calls":[]},"guilds_started",{"micros":73,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":55231,"calls":[]},"connect_finished",{"micros":55236,"calls":[]},"build_ready",{"micros":22,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":18,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: e98d09b87d0a4a0b47869547c1b09194).
2023-05-13T18:43:07 [     888] WARNING : gateway         @run              #142  : Shard ID None has stopped responding to the gateway. Closing and restarting.
2023-05-13T18:43:07 [     889] INFO    : gateway         @poll_event       #622  : Timed out receiving packet. Attempting a reconnect.
2023-05-13T18:43:07 [     889] INFO    : client          @connect          #556  : Got a request to RESUME the websocket.
2023-05-13T18:43:09 [     108] INFO    : gateway         @resume           #451  : Shard ID None has sent the RESUME payload.
2023-05-13T18:43:09 [     252] INFO    : gateway         @received_message #517  : Shard ID None session has been invalidated.
2023-05-13T18:43:09 [     385] INFO    : client          @connect          #556  : Got a request to IDENTIFY the websocket.
2023-05-13T18:43:14 [     708] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T18:43:15 [      30] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-ppfr",{"micros":174275,"calls":["id_created",{"micros":1088,"calls":[]},"session_lookup_time",{"micros":3509,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-2-185",{"micros":167869,"calls":["start_session",{"micros":80728,"calls":["discord-api-7c8b45696-778jd",{"micros":76496,"calls":["get_user",{"micros":16419},"get_guilds",{"micros":12047},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":1177},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":62,"calls":[]},"presence_started",{"micros":45425,"calls":[]},"guilds_started",{"micros":110,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":41492,"calls":[]},"connect_finished",{"micros":41497,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":24,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: dfa0abd4d12e51841e5ccaba0405a15b).
2023-05-13T18:48:17 [     375] INFO    : gateway         @poll_event       #622  : Timed out receiving packet. Attempting a reconnect.
2023-05-13T18:48:17 [     376] INFO    : client          @connect          #556  : Got a request to RESUME the websocket.
2023-05-13T18:48:17 [     385] ERROR   : client          @connect          #605  : Attempting a reconnect in 0.13s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:48:17 [     592] ERROR   : client          @connect          #605  : Attempting a reconnect in 0.73s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:48:18 [     351] ERROR   : client          @connect          #605  : Attempting a reconnect in 1.86s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:48:20 [     237] ERROR   : client          @connect          #605  : Attempting a reconnect in 2.23s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:48:22 [     488] ERROR   : client          @connect          #605  : Attempting a reconnect in 18.06s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:48:40 [     573] ERROR   : client          @connect          #605  : Attempting a reconnect in 61.50s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:49:42 [      94] ERROR   : client          @connect          #605  : Attempting a reconnect in 101.47s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:51:23 [     587] ERROR   : client          @connect          #605  : Attempting a reconnect in 92.15s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:52:55 [     756] ERROR   : client          @connect          #605  : Attempting a reconnect in 39.61s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:53:35 [     378] ERROR   : client          @connect          #605  : Attempting a reconnect in 358.48s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T18:59:33 [     879] ERROR   : client          @connect          #605  : Attempting a reconnect in 315.46s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T19:04:49 [     361] ERROR   : client          @connect          #605  : Attempting a reconnect in 418.45s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T19:11:47 [     838] ERROR   : client          @connect          #605  : Attempting a reconnect in 431.28s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T19:18:59 [     142] ERROR   : client          @connect          #605  : Attempting a reconnect in 1001.50s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T19:35:40 [     686] ERROR   : client          @connect          #605  : Attempting a reconnect in 787.67s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T19:48:48 [     384] ERROR   : client          @connect          #605  : Attempting a reconnect in 493.91s
Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 551, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\gateway.py", line 337, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 2869, in get_gateway
    data = await self.request(Route("GET", "/gateway"))
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 283, in request
    async with self.__session.request(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\aaaa\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [getaddrinfo failed]
2023-05-13T19:52:23 [     149] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T19:52:23 [     232] INFO    : client          @login            #513  : logging in using static token
2023-05-13T19:52:24 [     143] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T19:52:24 [     435] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-2gdq",{"micros":169817,"calls":["id_created",{"micros":2058,"calls":[]},"session_lookup_time",{"micros":2477,"calls":[]},"session_lookup_finished",{"micros":19,"calls":[]},"discord-sessions-prd-2-210",{"micros":164433,"calls":["start_session",{"micros":121139,"calls":["discord-api-7c8b45696-4kvg8",{"micros":114257,"calls":["get_user",{"micros":39924},"get_guilds",{"micros":19742},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":13}]}]},"starting_guild_connect",{"micros":58,"calls":[]},"presence_started",{"micros":357,"calls":[]},"guilds_started",{"micros":78,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":42750,"calls":[]},"connect_finished",{"micros":42755,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":22,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: f979f3e8457ea61717b8c52ef6917d5e).
2023-05-13T19:53:59 [     446] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T19:53:59 [     533] INFO    : client          @login            #513  : logging in using static token
2023-05-13T19:54:00 [     430] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T19:54:00 [     806] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-w1s2",{"micros":261762,"calls":["id_created",{"micros":1702,"calls":[]},"session_lookup_time",{"micros":2109,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-131",{"micros":257339,"calls":["start_session",{"micros":197455,"calls":["discord-api-7c8b45696-pt7sk",{"micros":192778,"calls":["get_user",{"micros":111406},"get_guilds",{"micros":6064},"send_scheduled_deletion_message",{"micros":13},"guild_join_requests",{"micros":279},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":52,"calls":[]},"presence_started",{"micros":266,"calls":[]},"guilds_started",{"micros":79,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":59432,"calls":[]},"connect_finished",{"micros":59438,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":27,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 43dc9dc833b7c0dffe0afaf9ca6d9fe6).
2023-05-13T19:55:39 [     479] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T19:55:39 [     537] INFO    : client          @login            #513  : logging in using static token
2023-05-13T19:55:40 [     413] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T19:55:40 [     649] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-4q8l",{"micros":117028,"calls":["id_created",{"micros":1088,"calls":[]},"session_lookup_time",{"micros":469,"calls":[]},"session_lookup_finished",{"micros":34,"calls":[]},"discord-sessions-prd-2-237",{"micros":111447,"calls":["start_session",{"micros":77430,"calls":["discord-api-7c8b45696-xxpp9",{"micros":71692,"calls":["get_user",{"micros":19424},"get_guilds",{"micros":3342},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":4832},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":56,"calls":[]},"presence_started",{"micros":439,"calls":[]},"guilds_started",{"micros":75,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":33374,"calls":[]},"connect_finished",{"micros":33379,"calls":[]},"build_ready",{"micros":25,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":39,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: f57bfda79fa08232452da986b78a03f0).
2023-05-13T19:57:46 [     300] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T19:57:46 [     375] INFO    : client          @login            #513  : logging in using static token
2023-05-13T19:57:47 [     598] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T19:57:47 [     836] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-726s",{"micros":125143,"calls":["id_created",{"micros":1896,"calls":[]},"session_lookup_time",{"micros":476,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-78",{"micros":121885,"calls":["start_session",{"micros":105491,"calls":["discord-api-7c8b45696-d9vbh",{"micros":100503,"calls":["get_user",{"micros":16531},"get_guilds",{"micros":24444},"send_scheduled_deletion_message",{"micros":9},"guild_join_requests",{"micros":5002},"authorized_ip_coro",{"micros":13}]}]},"starting_guild_connect",{"micros":59,"calls":[]},"presence_started",{"micros":359,"calls":[]},"guilds_started",{"micros":100,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":15792,"calls":[]},"connect_finished",{"micros":15798,"calls":[]},"build_ready",{"micros":26,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":49,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: c9de0cfa150fe0141379e6e9493df582).
2023-05-13T20:00:24 [     636] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:00:24 [     689] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:00:25 [     262] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:00:25 [     570] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-wz7g",{"micros":183958,"calls":["id_created",{"micros":1530,"calls":[]},"session_lookup_time",{"micros":3333,"calls":[]},"session_lookup_finished",{"micros":20,"calls":[]},"discord-sessions-prd-2-77",{"micros":177776,"calls":["start_session",{"micros":155342,"calls":["discord-api-7c8b45696-mflpc",{"micros":142141,"calls":["get_user",{"micros":43842},"get_guilds",{"micros":16218},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":8509},"authorized_ip_coro",{"micros":13}]}]},"starting_guild_connect",{"micros":67,"calls":[]},"presence_started",{"micros":303,"calls":[]},"guilds_started",{"micros":68,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":21936,"calls":[]},"connect_finished",{"micros":21943,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":31,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: d71f23973755f052ffe6bf5f24edc9ab).
2023-05-13T20:01:49 [     533] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:01:49 [     608] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:01:50 [     445] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:01:50 [     731] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-9n1r",{"micros":147247,"calls":["id_created",{"micros":2264,"calls":[]},"session_lookup_time",{"micros":2122,"calls":[]},"session_lookup_finished",{"micros":19,"calls":[]},"discord-sessions-prd-2-60",{"micros":141584,"calls":["start_session",{"micros":124139,"calls":["discord-api-7c8b45696-x5thc",{"micros":116620,"calls":["get_user",{"micros":49138},"get_guilds",{"micros":14846},"send_scheduled_deletion_message",{"micros":14},"guild_join_requests",{"micros":858},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":289,"calls":[]},"guilds_started",{"micros":82,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":16949,"calls":[]},"connect_finished",{"micros":16954,"calls":[]},"build_ready",{"micros":41,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":24,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 7becd2a3dabd4878008afabe2cbdb6c3).
2023-05-13T20:04:54 [     446] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:04:54 [     526] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:04:55 [     277] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:04:55 [     490] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-pbfj",{"micros":98175,"calls":["id_created",{"micros":1446,"calls":[]},"session_lookup_time",{"micros":400,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-164",{"micros":94026,"calls":["start_session",{"micros":70543,"calls":["discord-api-7c8b45696-2kckd",{"micros":62088,"calls":["get_user",{"micros":17734},"get_guilds",{"micros":3968},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":7145},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":79,"calls":[]},"presence_started",{"micros":331,"calls":[]},"guilds_started",{"micros":79,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":22948,"calls":[]},"connect_finished",{"micros":22952,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":21,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: 1262f30e7e757daf256e16962773a3f0).
2023-05-13T20:11:01 [     652] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:11:01 [     705] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:11:02 [     560] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:11:02 [     838] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-fvcf",{"micros":121518,"calls":["id_created",{"micros":1017,"calls":[]},"session_lookup_time",{"micros":515,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-98",{"micros":119505,"calls":["start_session",{"micros":102330,"calls":["discord-api-7c8b45696-jsn7q",{"micros":95209,"calls":["get_user",{"micros":36348},"get_guilds",{"micros":5464},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":7268},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":74,"calls":[]},"presence_started",{"micros":254,"calls":[]},"guilds_started",{"micros":90,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":16703,"calls":[]},"connect_finished",{"micros":16709,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":23,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: f9d4b98ac18b255b2f10a4cf6b4d7b47).
2023-05-13T20:12:15 [     253] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:12:15 [     328] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:12:16 [     761] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:12:16 [     938] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-99bz",{"micros":55801,"calls":["id_created",{"micros":1864,"calls":[]},"session_lookup_time",{"micros":367,"calls":[]},"session_lookup_finished",{"micros":21,"calls":[]},"discord-sessions-prd-2-103",{"micros":53024,"calls":["start_session",{"micros":48444,"calls":["discord-api-7c8b45696-c8scb",{"micros":43812,"calls":["get_user",{"micros":16191},"get_guilds",{"micros":4606},"send_scheduled_deletion_message",{"micros":9},"guild_join_requests",{"micros":633},"authorized_ip_coro",{"micros":9}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":2346,"calls":[]},"guilds_started",{"micros":88,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":2041,"calls":[]},"connect_finished",{"micros":2048,"calls":[]},"build_ready",{"micros":22,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":22,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: b0a136156cb76c516dcdb4bd834af8fe).
2023-05-13T20:13:00 [     688] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:13:00 [     738] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:13:01 [     421] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:13:01 [     592] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-255p",{"micros":55454,"calls":["id_created",{"micros":1984,"calls":[]},"session_lookup_time",{"micros":367,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-234",{"micros":51516,"calls":["start_session",{"micros":47030,"calls":["discord-api-7c8b45696-lr8jq",{"micros":42085,"calls":["get_user",{"micros":16058},"get_guilds",{"micros":3903},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":13}]}]},"starting_guild_connect",{"micros":54,"calls":[]},"presence_started",{"micros":309,"calls":[]},"guilds_started",{"micros":85,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":3985,"calls":[]},"connect_finished",{"micros":3990,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":24,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 84d81856bfb7f5af9a4517e94ac3164e).
2023-05-13T20:16:19 [     642] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:17:01 [     751] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:17:01 [     873] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:17:02 [     516] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:17:02 [     724] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-rms3",{"micros":94214,"calls":["id_created",{"micros":1209,"calls":[]},"session_lookup_time",{"micros":2540,"calls":[]},"session_lookup_finished",{"micros":23,"calls":[]},"discord-sessions-prd-2-203",{"micros":88591,"calls":["start_session",{"micros":43821,"calls":["discord-api-7c8b45696-b9p4j",{"micros":39737,"calls":["get_user",{"micros":12245},"get_guilds",{"micros":5936},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":270},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":60,"calls":[]},"presence_started",{"micros":28701,"calls":[]},"guilds_started",{"micros":103,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":15850,"calls":[]},"connect_finished",{"micros":15855,"calls":[]},"build_ready",{"micros":23,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":23,"calls":[]},"split_ready",{"micros":2,"calls":[]}]}]}] (Session ID: 1ab76180ecf182ea007581e639b967ce).
2023-05-13T20:24:41 [     331] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:24:41 [     403] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:24:42 [     249] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:24:42 [     453] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-wwpd",{"micros":84137,"calls":["id_created",{"micros":3097,"calls":[]},"session_lookup_time",{"micros":5943,"calls":[]},"session_lookup_finished",{"micros":21,"calls":[]},"discord-sessions-prd-2-31",{"micros":74423,"calls":["start_session",{"micros":46984,"calls":["discord-api-7c8b45696-qlm42",{"micros":42096,"calls":["get_user",{"micros":12814},"get_guilds",{"micros":4891},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":948},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":74,"calls":[]},"presence_started",{"micros":26895,"calls":[]},"guilds_started",{"micros":82,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":335,"calls":[]},"connect_finished",{"micros":341,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":24,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 81f4c397f2715b5d7dba9d01435109ac).
2023-05-13T20:26:13 [     280] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:26:13 [     361] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:26:13 [     946] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:26:14 [     180] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-f6dh",{"micros":109440,"calls":["id_created",{"micros":986,"calls":[]},"session_lookup_time",{"micros":367,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-60",{"micros":107538,"calls":["start_session",{"micros":61843,"calls":["discord-api-7c8b45696-w68jt",{"micros":58655,"calls":["get_user",{"micros":18439},"get_guilds",{"micros":4759},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":3976},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":82,"calls":[]},"presence_started",{"micros":37562,"calls":[]},"guilds_started",{"micros":74,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":7930,"calls":[]},"connect_finished",{"micros":7934,"calls":[]},"build_ready",{"micros":17,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":23,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: abd8df29b0369ef983fdde6d971463e8).
2023-05-13T20:27:58 [     866] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:27:58 [     946] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:27:59 [     728] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:28:00 [      40] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-4m58",{"micros":172566,"calls":["id_created",{"micros":1150,"calls":[]},"session_lookup_time",{"micros":423,"calls":[]},"session_lookup_finished",{"micros":18,"calls":[]},"discord-sessions-prd-2-278",{"micros":170630,"calls":["start_session",{"micros":107706,"calls":["discord-api-7c8b45696-wrh7g",{"micros":103018,"calls":["get_user",{"micros":18599},"get_guilds",{"micros":6610},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":338,"calls":[]},"guilds_started",{"micros":103,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":62334,"calls":[]},"connect_finished",{"micros":62340,"calls":[]},"build_ready",{"micros":47,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":39,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 2cd8222b14204f9a10af3193688391bb).
2023-05-13T20:29:12 [       8] WARNING : client          @__init__         #253  : PyNaCl is not installed, voice will NOT be supported
2023-05-13T20:29:12 [      82] INFO    : client          @login            #513  : logging in using static token
2023-05-13T20:29:12 [     975] INFO    : gateway         @identify         #437  : Shard ID None has sent the IDENTIFY payload.
2023-05-13T20:29:13 [     238] INFO    : gateway         @received_message #531  : Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-b0k4",{"micros":142635,"calls":["id_created",{"micros":1745,"calls":[]},"session_lookup_time",{"micros":5450,"calls":[]},"session_lookup_finished",{"micros":23,"calls":[]},"discord-sessions-prd-2-228",{"micros":134891,"calls":["start_session",{"micros":77659,"calls":["discord-api-7c8b45696-4jlqj",{"micros":73239,"calls":["get_user",{"micros":29291},"get_guilds",{"micros":7934},"send_scheduled_deletion_message",{"micros":13},"guild_join_requests",{"micros":1722},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":51,"calls":[]},"presence_started",{"micros":38821,"calls":[]},"guilds_started",{"micros":94,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":18206,"calls":[]},"connect_finished",{"micros":18212,"calls":[]},"build_ready",{"micros":23,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":27,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: aa37f8bc2d233e5e2e1c16d36d00456e).
